# Generated by Django 4.1.3 on 2023-10-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educationlevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Educationlevel', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=128)),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='classes',
            old_name='class_credit',
            new_name='class_age',
        ),
        migrations.RenameField(
            model_name='classes',
            old_name='class_category',
            new_name='class_department',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='category',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='class_year',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='on_register',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='teacher',
        ),
        migrations.AddField(
            model_name='classes',
            name='class_gender',
            field=models.CharField(default='ชาย', max_length=10),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_name',
            field=models.CharField(max_length=100),
        ),
    ]
