# Generated by Django 4.1.3 on 2023-10-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0002_educationlevel_gender_rename_category_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_gender',
            field=models.CharField(max_length=10),
        ),
    ]
