# Generated by Django 4.1.3 on 2023-10-02 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0003_alter_classes_class_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_name', models.CharField(max_length=100)),
                ('detail_age', models.IntegerField()),
                ('detail_Educationlevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empapp.educationlevel')),
                ('detail_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empapp.department')),
                ('detail_gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empapp.gender')),
            ],
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
    ]
