# Generated by Django 4.1.3 on 2023-10-02 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0004_detail_delete_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='detail_Educationlevel',
        ),
    ]
