# Generated by Django 4.1.3 on 2023-10-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0007_rename_education_education_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='detail_education',
            field=models.CharField(default='ประถมศึกษา', max_length=100),
        ),
    ]
