# Generated by Django 4.1.3 on 2023-10-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0009_alter_detail_detail_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='detail_lastname',
            field=models.CharField(default='ไม่ระบุ', max_length=100),
        ),
    ]
